#!/usr/bin/env bash
set -Eeuo pipefail

: "${LIMA_ACCEL_MODE:=auto}"

if [ $# -lt 1 ]; then
  echo "Usage: lima-up <template.yaml|image.qcow2|image.img|image.raw|instance> [-- limactl args...]" >&2
  exit 1
fi

target="$1"
shift || true

# Auto-generate a Lima template when a raw disk image is provided directly.
case "${target,,}" in
  *.qcow2|*.img|*.raw)
    if [ ! -f "$target" ]; then
      echo "Disk image not found: $target" >&2
      exit 1
    fi
    abs_image_path="$(realpath "$target")"
    img_name="$(basename "${target%.*}")"
    case "$(uname -m)" in
      x86_64|amd64)   vm_arch="x86_64" ;;
      aarch64|arm64)  vm_arch="aarch64" ;;
      *) echo "Unsupported host arch: $(uname -m)" >&2; exit 1 ;;
    esac
    target="/tmp/${img_name}.yaml"
    cat > "$target" <<EOF
# Auto-generated by lima-up from disk image.
images:
  - location: "$abs_image_path"
    arch: "$vm_arch"
cpus: 2
memory: "4GiB"
mounts:
  - location: "/workspace"
    writable: true
video:
  display: "vnc"
containerd:
  system: false
  user: false
EOF
    echo "Auto-generated Lima template for disk image: $abs_image_path" >&2
    ;;
  *.iso)
    if [ ! -f "$target" ]; then
      echo "ISO file not found: $target" >&2
      exit 1
    fi
    abs_iso_path="$(realpath "$target")"
    iso_name="$(basename "${target%.*}")"
    case "$(uname -m)" in
      x86_64|amd64)   vm_arch="x86_64" ;;
      aarch64|arm64)  vm_arch="aarch64" ;;
      *) echo "Unsupported host arch: $(uname -m)" >&2; exit 1 ;;
    esac

    # Create a blank qcow2 disk for the OS to install onto.
    blank_disk="/tmp/${iso_name}-disk.qcow2"
    if [ ! -f "$blank_disk" ]; then
      qemu-img create -f qcow2 "$blank_disk" 60G
      echo "Created blank 60G disk for ISO install: $blank_disk" >&2
    fi

    # Export LIMA_CDROM so qemu-tcg-wrapper injects -cdrom.
    export LIMA_CDROM="$abs_iso_path"

    target="/tmp/${iso_name}.yaml"
    cat > "$target" <<EOF
# Auto-generated by lima-up from ISO image.
# The ISO is attached as a CD-ROM via LIMA_CDROM env + qemu-tcg-wrapper.
images:
  - location: "$blank_disk"
    arch: "$vm_arch"
cpus: 4
memory: "8GiB"
firmware:
  legacyBIOS: false
mounts: []
video:
  display: "vnc"
containerd:
  system: false
  user: false
EOF
    echo "Auto-generated Lima template for ISO boot: $abs_iso_path" >&2
    ;;
esac

# TCG environment overrides — rewrite KVM-only QEMU args to software-emulation equivalents.
# Used when KVM is unavailable (auto mode) or explicitly requested (tcg mode).
# qemu-tcg-wrapper also fixes missing OVMF VARS pflash and machine type args.
tcg_qemu_env=(
  'QEMU_SYSTEM_X86_64=qemu-tcg-wrapper'
  'QEMU_SYSTEM_AARCH64=qemu-system-aarch64 -machine virt,acpi=off,accel=tcg'
  'QEMU_SYSTEM_RISCV64=qemu-system-riscv64 -machine virt,acpi=off,accel=tcg'
  'QEMU_SYSTEM_ARM=qemu-system-arm -machine virt,accel=tcg'
  'QEMU_SYSTEM_PPC64=qemu-system-ppc64 -machine pseries,accel=tcg'
  'QEMU_SYSTEM_S390X=qemu-system-s390x -machine s390-ccw-virtio,accel=tcg'
)

qemu_env=()

# Pass LIMA_CDROM and LIMA_TPM_DIR through to QEMU wrapper if set.
if [ -n "${LIMA_CDROM:-}" ]; then
  qemu_env+=("LIMA_CDROM=${LIMA_CDROM}")
fi
if [ -n "${LIMA_TPM_DIR:-}" ]; then
  qemu_env+=("LIMA_TPM_DIR=${LIMA_TPM_DIR}")
fi

case "${LIMA_ACCEL_MODE}" in
  auto)
    if [ ! -e /dev/kvm ]; then
      qemu_env=("${tcg_qemu_env[@]}")
      echo "LIMA_ACCEL_MODE=auto: /dev/kvm not found; forcing QEMU TCG mode." >&2
    fi
    ;;
  tcg)
    qemu_env=("${tcg_qemu_env[@]}")
    echo "LIMA_ACCEL_MODE=tcg: forcing QEMU software emulation." >&2
    ;;
  kvm)
    echo "LIMA_ACCEL_MODE=kvm: using KVM acceleration when available." >&2
    ;;
  *)
    echo "Invalid LIMA_ACCEL_MODE='${LIMA_ACCEL_MODE}'. Expected one of: auto, kvm, tcg." >&2
    exit 1
    ;;
esac

# Determine instance name from path (basename without extension) or use as-is.
instance_name=""
if [ -f "$target" ]; then
  instance_name="$(basename "$target" .yaml)"
  # If a stopped instance already exists for this template, just restart it.
  if lima-as-user limactl list --format "{{.Name}}" 2>/dev/null | grep -qx "$instance_name"; then
    echo "Instance '${instance_name}' already exists. Starting existing instance." >&2
    lima-as-user env "${qemu_env[@]}" limactl start "$instance_name" "$@"
  else
    lima-as-user env "${qemu_env[@]}" limactl start "$target" "$@"
  fi
else
  instance_name="$target"
  lima-as-user env "${qemu_env[@]}" limactl start "$target" "$@"
fi

# Read the VNC password Lima generated for this instance.
vnc_password=""
vnc_password_file="${LIMA_HOME:-/var/lib/lima}/${instance_name}/vncpassword"
if [ -f "$vnc_password_file" ]; then
  vnc_password="$(cat "$vnc_password_file")"
fi

# Attempt to discover the qemu VNC listener created by Lima, then retarget noVNC.
if port="$(lima-detect-vnc-port)"; then
  lima-use-vnc-port "$port"
  url="http://127.0.0.1:${WEB_PORT:-8006}/vnc.html?autoconnect=1&resize=remote&path=websockify"
  if [ -n "$vnc_password" ]; then
    url="${url}&password=${vnc_password}"
  fi
  echo "Open noVNC: ${url}"
  echo "VM login  — username: ${LIMA_USER:-lima}  password: lima"
else
  echo "Lima started, but VNC port detection failed. Set manually with: lima-use-vnc-port <port>" >&2
fi
