#!/usr/bin/env bash
set -Eeuo pipefail

: "${LIMA_ACCEL_MODE:=auto}"

if [ $# -lt 1 ]; then
  echo "Usage: lima-up <template.yaml|image.qcow2|image.img|image.raw|instance> [-- limactl args...]" >&2
  exit 1
fi

target="$1"
shift || true

# Auto-generate a Lima template when a raw disk image is provided directly.
case "${target,,}" in
  *.qcow2|*.img|*.raw)
    if [ ! -f "$target" ]; then
      echo "Disk image not found: $target" >&2
      exit 1
    fi
    abs_image_path="$(realpath "$target")"
    img_name="$(basename "${target%.*}")"
    case "$(uname -m)" in
      x86_64|amd64)   vm_arch="x86_64" ;;
      aarch64|arm64)  vm_arch="aarch64" ;;
      *) echo "Unsupported host arch: $(uname -m)" >&2; exit 1 ;;
    esac
    target="/tmp/${img_name}.yaml"
    cat > "$target" <<EOF
# Auto-generated by lima-up from disk image.
images:
  - location: "$abs_image_path"
    arch: "$vm_arch"
cpus: 2
memory: "4GiB"
mounts:
  - location: "/workspace"
    writable: true
video:
  display: "vnc"
containerd:
  system: false
  user: false
EOF
    echo "Auto-generated Lima template for disk image: $abs_image_path" >&2
    ;;
esac

# TCG environment overrides — rewrite KVM-only QEMU args to software-emulation equivalents.
# Used when KVM is unavailable (auto mode) or explicitly requested (tcg mode).
# qemu-tcg-wrapper also fixes missing OVMF VARS pflash and machine type args.
tcg_qemu_env=(
  'QEMU_SYSTEM_X86_64=qemu-tcg-wrapper'
  'QEMU_SYSTEM_AARCH64=qemu-system-aarch64 -machine virt,acpi=off,accel=tcg'
  'QEMU_SYSTEM_RISCV64=qemu-system-riscv64 -machine virt,acpi=off,accel=tcg'
  'QEMU_SYSTEM_ARM=qemu-system-arm -machine virt,accel=tcg'
  'QEMU_SYSTEM_PPC64=qemu-system-ppc64 -machine pseries,accel=tcg'
  'QEMU_SYSTEM_S390X=qemu-system-s390x -machine s390-ccw-virtio,accel=tcg'
)

qemu_env=()
case "${LIMA_ACCEL_MODE}" in
  auto)
    if [ ! -e /dev/kvm ]; then
      qemu_env=("${tcg_qemu_env[@]}")
      echo "LIMA_ACCEL_MODE=auto: /dev/kvm not found; forcing QEMU TCG mode." >&2
    fi
    ;;
  tcg)
    qemu_env=("${tcg_qemu_env[@]}")
    echo "LIMA_ACCEL_MODE=tcg: forcing QEMU software emulation." >&2
    ;;
  kvm)
    echo "LIMA_ACCEL_MODE=kvm: using KVM acceleration when available." >&2
    ;;
  *)
    echo "Invalid LIMA_ACCEL_MODE='${LIMA_ACCEL_MODE}'. Expected one of: auto, kvm, tcg." >&2
    exit 1
    ;;
esac

# Determine instance name from path (basename without extension) or use as-is.
if [ -f "$target" ]; then
  instance_name="$(basename "$target" .yaml)"
  # If a stopped instance already exists for this template, just restart it.
  if lima-as-user limactl list --format "{{.Name}}" 2>/dev/null | grep -qx "$instance_name"; then
    echo "Instance '${instance_name}' already exists. Starting existing instance." >&2
    lima-as-user env "${qemu_env[@]}" limactl start "$instance_name" "$@"
  else
    lima-as-user env "${qemu_env[@]}" limactl start "$target" "$@"
  fi
else
  lima-as-user env "${qemu_env[@]}" limactl start "$target" "$@"
fi

# Attempt to discover the qemu VNC listener created by Lima, then retarget noVNC.
if port="$(lima-detect-vnc-port)"; then
  lima-use-vnc-port "$port"
  echo "Open noVNC: http://127.0.0.1:${WEB_PORT:-8006}/vnc.html?autoconnect=1&resize=remote&path=websockify"
else
  echo "Lima started, but VNC port detection failed. Set manually with: lima-use-vnc-port <port>" >&2
fi
